### ISSUE TITLE
Invalid Product Code on windows 11

### ISSUE THREAD

**Issue by leocas18** [neuralpain/qbactivator#12]
I have tried the new activator and even the very first activator on a Fresh Installation of Windows 11, I get it installed and when the activator goes to the other stage to open the app to get it activated I keep getting Invalid Product Code and the app closes. I Reinstalled using a different product #, rebooting the system, tried on another laptop with Fresh Windows 11 installation and I get the same Invalid Product Code. When the activator is closed I tried reopening the app and it opens fine just that it has 5 days to register and does not give invalid product code.   I tried on fresh installation of Windows 10 early release and it works. 
HELP, something with Windows 11 and the activator triggers the Invalid Product Code.

**Comment by neuralpain** [comment]
Hi. What version of QuickBooks are you attempting to install?

Please give [this video](https://youtu.be/4mMRHUcG6UM) a watch as well for correct activation. Note that the video shows download of the installer through qbactivator but the installation and activation steps remain the same if you already have an installer downloaded.

**Comment by leocas18** [comment]
Hi,  Im using v19 and tried v18 as well.

https://user-images.githubusercontent.com/121475453/226429396-734e0f5a-9856-4a0a-99b2-43c7d606cea0.mp4

**Comment by neuralpain** [comment]
Do an uninstall of QuickBooks POS and reinstall using the activator. If you need further assistance, contact me via [Telegram](https://t.me/neuralpain) where I may be able to thoroughly assist.

**Comment by neuralpain** [comment]
> Do an uninstall of QuickBooks POS and reinstall using the activator. If you need further assistance, contact me via [Telegram](https://t.me/neuralpain) where I may be able to thoroughly assist with RDP.

In reference to my last comment:

You could get an "Invalid Product Number" error if there are compromised files in the Entitlement folder. When the activator invokes the installer it removes all files that could possibly cause errors after the install to ensure a perfect, clean installation.

This reason is why I suggest an uninstall of QuickBooks POS and then a reinstall invoked **by** the activator. There should be no room for errors after the installation if it was done this way.

--

As mentioned before, if the error still persists I would need to investigate further via [RDP](https://t.me/neuralpain).
